### ISSUE TITLE
Question regarding app sandboxing

### ISSUE THREAD

**Issue by clementmiao** [sindresorhus/do-not-disturb#2]
Hi,

I love your project!

I had a question regarding App Sandboxing. How does your app bypass the need to grant permissions regarding modifying the user preferences? I'm trying to make a macOS app for fun that partially uses your library here. I'm hitting issues where after building in Xcode, I run it and it says it turned DnD on, but it doesn't look like it on my computer. I figured it must be a code signing or App Sandboxing issue.

It would be greatly appreciated if you had any insight on this while making this! Appreciate it.

**Comment by sindresorhus** [comment]
This unfortunately does not work with sandboxing.

**Comment by sindresorhus** [comment]
To make it work with sandboxing, you need to request accessibility access and use AppleScript instead: https://stackoverflow.com/questions/25210120/is-it-possible-to-turn-on-off-do-not-disturb-for-os-x-programmatically
