### ISSUE TITLE
Setting `do-not-disturb off` does not reflect dnd mode being off in the menubar

### ISSUE THREAD

**Issue by megalithic** [sindresorhus/do-not-disturb#5]
Using newly installed instance of 10.14 (Mojave) with `do-not-disturb-cli` v0.2.0 installed, `do-not disturb off` after previously setting `do-not-disturb on` does not seem to update the menubar icon to reflect that dnd mode is now off. I'm not sure if it actually is still on or not. It may just be that the icon isn't updating properly. Will work on verifying that.

At any rate, just wanted to file this issue in the event that others are experiencing this.

**Comment by mellson** [comment]
Just a suggestion, I would think this happens because the app is sandboxed. If the app is not sandboxed it should work.
