### ISSUE TITLE
Electron path in development

### ISSUE THREAD

**Issue by stvmlbrn** [sindresorhus/do-not-disturb#7]
Having some issues with the `bin` path in an electron app during development. The issue seems to be related to the line `const bin = path.join(electronUtil.fixPathForAsarUnpack(__dirname), 'do-not-disturb');` in `index.js`.

If I change it to `const bin = path.join(__dirname, '/node_modules/@sindresorhus/do-not-disturb/do-not-disturb');` it works.

Maybe this would support electron with and without asar while also working in node apps? 
```js
let bin = path.join(
  electronUtil.fixPathForAsarUnpack(__dirname),
  'do-not-disturb'
);

if (electronUtil.isElectron && !electronUtil.isUsingAsar) {
  bin = path.join(
    __dirname,
    '/node_modules/@sindresorhus/do-not-disturb/do-not-disturb'
  );
}
```

**Comment by sindresorhus** [comment]
`fixPathForAsarUnpack` already checks for ASAR: https://github.com/sindresorhus/electron-util/blob/c0b2762646fdcaea16e3b826b597771a19d7aa3a/node.js#L9

**Comment by noahlaux** [comment]
I have the same issue. The module doesn't work in development or packaged. If I do `path.join('do-not-disturb');` it's good.
